name: shard_xl
description: "ShardXL - Minecraft Java Edition Launcher for Desktop & Android"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Storage
  shared_preferences: ^2.3.4

  # Window Management (Desktop)
  window_manager: ^0.4.3

  # Minecraft Launcher
  dartcraft: ^1.0.1

  # Image Picker
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/